# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JoinBoardGame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JoinBoardGame
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'


  # Pods for Facebook
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  # Pods for Google Sign In
  pod 'GoogleSignIn'

  # Pods for ImagePicker
  pod 'ImagePicker'
  pod 'JSQMessagesViewController'
  pod 'MessageKit'

end
